-- MySQL Script generated by MySQL Workbench
-- 03/11/18 06:00:05
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='TRADITIONAL,ALLOW_INVALID_DATES';

-- -----------------------------------------------------
-- Schema venturismo
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `venturismo` ;

-- -----------------------------------------------------
-- Schema venturismo
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `venturismo` DEFAULT CHARACTER SET utf8 ;
USE `venturismo` ;

-- -----------------------------------------------------
-- Table `venturismo`.`cliente`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`cliente` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`cliente` (
  `idcliente` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(50) NULL,
  `edad` INT NULL,
  `telefono` VARCHAR(45) NULL,
  `correo` VARCHAR(60) NULL,
  `direccion` VARCHAR(300) NULL,
  `contraseña` VARCHAR(45) NULL,
  PRIMARY KEY (`idcliente`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`terminal_agencia`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`terminal_agencia` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`terminal_agencia` (
  `idterminal` INT NOT NULL AUTO_INCREMENT,
  `nombre` VARCHAR(100) NULL,
  `direccion` VARCHAR(300) NULL,
  `reputacion` VARCHAR(50) NULL,
  `terminalAgencia` VARCHAR(200) NULL,
  PRIMARY KEY (`idterminal`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`itinerario`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`itinerario` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`itinerario` (
  `iditinerario` INT NOT NULL AUTO_INCREMENT,
  `ciudad_origen` VARCHAR(45) NULL,
  `ciudad_destino` VARCHAR(45) NULL,
  `hora_salida` TIME NULL,
  `fecha_viaje` DATE NULL,
  `hora_aproxllegada` TIME NULL,
  PRIMARY KEY (`iditinerario`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`viaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`viaje` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`viaje` (
  `numero_viaje` INT NOT NULL,
  `estatus` VARCHAR(45) NULL,
  `capacidad` INT NULL,
  `cantidad_pasajeros` INT NULL,
  `terminal_agencia_idterminal` INT NOT NULL,
  `itinerario_iditinerario` INT NOT NULL,
  PRIMARY KEY (`numero_viaje`),
  INDEX `fk_terminal_agencia_viaje1_idx` (`terminal_agencia_idterminal` ASC),
  INDEX `fk_itinerario_viaje1_idx` (`itinerario_iditinerario` ASC),
  CONSTRAINT `fk_terminal_agencia_viaje1`
    FOREIGN KEY (`terminal_agencia_idterminal`)
    REFERENCES `venturismo`.`terminal_agencia` (`idterminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_itinerario_viaje1`
    FOREIGN KEY (`itinerario_iditinerario`)
    REFERENCES `venturismo`.`itinerario` (`iditinerario`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`tracking`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`tracking` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`tracking` (
  `numero_tracking` VARCHAR(20) NOT NULL,
  `ciudad_origen` VARCHAR(45) NULL,
  `ciudad_destino` VARCHAR(45) NULL,
  `hora_llegada` TIME NULL,
  `hora_salida` TIME NULL,
  `estatus` VARCHAR(100) NULL,
  `terminal_agencia_idterminal` INT NOT NULL,
  `viaje_numero_viaje` INT NOT NULL,
  PRIMARY KEY (`numero_tracking`),
  INDEX `fk_terminal_agencia_tracking1_idx` (`terminal_agencia_idterminal` ASC),
  INDEX `fk_viaje_tracking1_idx` (`viaje_numero_viaje` ASC),
  CONSTRAINT `fk_terminal_agencia_tracking1`
    FOREIGN KEY (`terminal_agencia_idterminal`)
    REFERENCES `venturismo`.`terminal_agencia` (`idterminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_tracking1`
    FOREIGN KEY (`viaje_numero_viaje`)
    REFERENCES `venturismo`.`viaje` (`numero_viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`pasaje`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`pasaje` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`pasaje` (
  `numero_pasaje` INT NOT NULL,
  `numero_asiento` INT NULL,
  `costo` FLOAT NULL,
  `cliente_idcliente` INT NOT NULL,
  `terminal_agencia_idterminal` INT NOT NULL,
  `viaje_numero_viaje` INT NOT NULL,
  PRIMARY KEY (`numero_pasaje`),
  INDEX `fk_cliente_pasaje1_idx` (`cliente_idcliente` ASC),
  INDEX `fk_terminal_agencia_pasaje1_idx` (`terminal_agencia_idterminal` ASC),
  INDEX `fk_viaje_pasaje1_idx` (`viaje_numero_viaje` ASC),
  CONSTRAINT `fk_cliente_pasaje1`
    FOREIGN KEY (`cliente_idcliente`)
    REFERENCES `venturismo`.`cliente` (`idcliente`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_terminal_agencia_pasaje1`
    FOREIGN KEY (`terminal_agencia_idterminal`)
    REFERENCES `venturismo`.`terminal_agencia` (`idterminal`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_viaje_pasaje1`
    FOREIGN KEY (`viaje_numero_viaje`)
    REFERENCES `venturismo`.`viaje` (`numero_viaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`compra`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`compra` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`compra` (
  `idcompra` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `pasaje_numero_pasaje` INT NOT NULL,
  PRIMARY KEY (`idcompra`),
  INDEX `fk_pasaje_compra1_idx` (`pasaje_numero_pasaje` ASC),
  CONSTRAINT `fk_pasaje_compra1`
    FOREIGN KEY (`pasaje_numero_pasaje`)
    REFERENCES `venturismo`.`pasaje` (`numero_pasaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `venturismo`.`reserva`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `venturismo`.`reserva` ;

CREATE TABLE IF NOT EXISTS `venturismo`.`reserva` (
  `idreserva` INT NOT NULL AUTO_INCREMENT,
  `fecha` DATE NULL,
  `pasaje_numero_pasaje` INT NOT NULL,
  PRIMARY KEY (`idreserva`),
  INDEX `fk_pasaje_reserva1_idx` (`pasaje_numero_pasaje` ASC),
  CONSTRAINT `fk_pasaje_reserva1`
    FOREIGN KEY (`pasaje_numero_pasaje`)
    REFERENCES `venturismo`.`pasaje` (`numero_pasaje`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
